apiVersion: networking.k8s.io/v1

# Ingress is a Kubernetes resource that manages external access to services in a cluster, typically HTTP.
kind: Ingress

metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1

spec:
  rules:
    - host: taito-devops-workshop.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: client
                port:
                  number: {{ .Values.client.service.port }}
          - path: /api/(.*)
            pathType: Prefix
            backend:
              service:
                name: server
                port:
                  number: {{ .Values.server.service.port }}
