apiVersion: v1

# Service is a Kubernetes resource that exposes an application running on a set of Pods as a network service.
kind: Service

metadata:
  name: server

# Spec defines the behavior of the service: which pods it should target, which ports it should expose, etc.
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: {{ .Values.server.service.port }}
  selector:
    app: server
